apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  selector:
    app: api-server # 'app: api-server' 라벨 붙은 파드 찾기
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80