apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: trackfit-cluster
  region: ap-northeast-2
  version: "1.28"

managedNodeGroups:
  - name: nodegroup-1
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    ssh:
      allow: true