apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml