apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: public.ecr.aws/s6u6a7r0/worker:latest

        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret